apiVersion: v1
kind: Service
metadata:
  name: flutter-web
spec:
  type: NodePort
  selector:
    app: flutter-web
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30010
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flutter-web
  labels:
    app: flutter-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flutter-web
  template:
    metadata:
      labels:
        app: flutter-web
    spec:
      containers:
        - name: flutter-web
          image: rihabbennour/flutter-web:latest
          ports:
            - containerPort: 80
